[build]
  command = "npm ci && npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL,NEXT_PUBLIC_STRIPE_PRICE_ID_INDEX_PRO,NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE,STRIPE_PUBLISHABLE_KEY,NEXT_PUBLIC_APP_URL" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg","drizzle-orm"]

# Background function for LLM-intensive agents (15-minute timeout)
[functions."background-agents"]
  timeout = 900  # 15 minutes for LLM processing


# Scheduled function to process the leaderboard evaluation queue every 30 minutes
[functions."scheduled-leaderboard-queue"]
  schedule = "*/30 * * * *"
